### NUMPY

In [1]:
import numpy as np

In [2]:
a = np.array([[1,1,2,3,4,4],
              [2,3,4,4,6,5],
              [4,5,6,3,4,5]])

a.ndim

2

the shape attribute gives the number of columns and rows 

size attributes gives the total number of elements

In [21]:
print(a.size, a.shape)
a

18 (3, 6)


array([[1, 1, 2, 3, 4, 4],
       [2, 3, 4, 4, 6, 5],
       [4, 5, 6, 3, 4, 5]])

In [20]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

linspace can be used to create a sequence of numbers that have been spaced equally( Start, Stop, Spacing factor)

In [26]:
np.linspace(1,10,20)

array([ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684,
        3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789,
        5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895,
        8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ])

In [31]:
a.reshape(6,3)


array([[1, 1, 2],
       [3, 4, 4],
       [2, 3, 4],
       [4, 6, 5],
       [4, 5, 6],
       [3, 4, 5]])

ravel flattens the array into one list

In [32]:
a.ravel()

array([1, 1, 2, 3, 4, 4, 2, 3, 4, 4, 6, 5, 4, 5, 6, 3, 4, 5])

In [36]:
a.min(), a.max()


(1, 6)

In [11]:
b=np.linspace(1,20,20)
b

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
       14., 15., 16., 17., 18., 19., 20.])

In [12]:
b[[0,3,-1]]

array([ 1.,  4., 20.])

In [3]:
c=np.array([[1,2,3],
            [4,5,6],
            [7,8,9]])
c

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [19]:
c[:,:2]

array([[1, 2],
       [4, 5],
       [7, 8]])

In [22]:
b

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
       14., 15., 16., 17., 18., 19., 20.])

In [26]:
b.sum()

210.0

In [28]:
b.var()

33.25

In [27]:
b.std()

5.766281297335398

In [29]:
b.mean()

10.5

In [30]:
c

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [31]:
c.sum(axis=0)

array([12, 15, 18])

In [39]:
c.sum(axis=1)

array([ 6, 15, 24])

In [32]:
c.sum()

45

In [37]:
c.mean(axis=0)

array([4., 5., 6.])

In [35]:
c.mean(axis=1)

array([2., 5., 8.])

In [4]:
c

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [6]:
c[:,:1]

array([[1],
       [4],
       [7]])