Opeerations and Boolean arrays

In [2]:
import numpy as np

In [3]:
a= np.arange(5)

In [4]:
a

array([0, 1, 2, 3, 4])

In [5]:
a + 5

array([5, 6, 7, 8, 9])

In [6]:
a*2

array([0, 2, 4, 6, 8])

In [7]:
a[[True,True,False,False,True]]

array([0, 1, 4])

In [8]:
a>=2

array([False, False,  True,  True,  True])

In [9]:
a[a>=2]

array([2, 3, 4])

In [10]:
a.mean()

2.0

In [11]:
a[a>a.mean()]

array([3, 4])

In [12]:
a[(a==6)|(a<2)]

array([0, 1])

In [13]:
R=np.random.randint(50, size=(3,3))

In [14]:
R

array([[26, 47,  1],
       [10, 11, 36],
       [12,  8, 13]])

In [15]:
R<30

array([[ True, False,  True],
       [ True,  True, False],
       [ True,  True,  True]])

In [16]:
R[R<30]

array([26,  1, 10, 11, 12,  8, 13])